# Generated by Django 5.2.2 on 2025-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='browser_signature',
            field=models.TextField(blank=True, help_text='Full browser fingerprint/configuration'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active_profile',
            field=models.BooleanField(default=True, help_text='Whether this profile should be used'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_connected',
            field=models.BooleanField(default=False, help_text='Whether the user is currently connected'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='en-US', help_text='Browser language setting', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_rotation',
            field=models.DateTimeField(blank=True, help_text='When to rotate to next profile', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_id',
            field=models.CharField(help_text='Unique identifier for browser profile', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='proxy_address',
            field=models.CharField(blank=True, help_text='Proxy address in format IP:PORT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Browser user agent string', max_length=255),
        ),
    ]
