# Generated by Django 5.2.2 on 2025-06-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_id',
            field=models.CharField(blank=True, help_text='Unique identifier for browser profile', max_length=50, null=True, unique=True),
        ),
    ]
